### ISSUE TITLE
Entry api for Map is slower than array equivalent

### ISSUE THREAD

**Issue by udoprog** [udoprog/fixed-map#34]
With benches introduced in #33 I've noticed that the abstracted entry API is slower than doing the equivalent over an array:

```
entry/fixed/32          time:   [6.9914 ns 6.9959 ns 7.0010 ns]
entry/array/32          time:   [213.54 ps 214.13 ps 214.75 ps]
```

> To run a bench, I used use: `cargo bench -- entry/fixed/32` and `cargo bench -- entry/array/32`.

The slowdown increases with time, at 4 elements it's the same but increases after it (so it's probably inline hinting which is not firing properly):

```
entry/fixed/4           time:   [209.29 ps 210.74 ps 212.19 ps]
entry/fixed/8           time:   [3.9445 ns 3.9611 ns 3.9782 ns]
entry/fixed/16          time:   [4.5784 ns 4.6329 ns 4.7035 ns]
entry/fixed/32          time:   [6.7929 ns 6.8126 ns 6.8305 ns]
```

This isn't unexpected, we had a similar issue due to inability to inline code before which was addressed in #23 and subsequent PRs. It would be nice to investigate if something similar is possible with the entry API.

CC: @pitaj if you're curious to investigate as well.

**Comment by udoprog** [comment]
Another reason why inlining might struggle is because we're operating through the `Entry` enum.

**Comment by pitaj** [comment]
I'm not seeing inline(always) used anywhere in the std HashMap 

Another place to check for pessimization is option-bucket.

**Comment by udoprog** [comment]
Ah yeah. There's a lot of places where we didn't add `#[inline]` in `option-bucket`, we should add those, but despite adding them locally I'm not seeing any improvements.

This will most likely boil down to having to break it down into a simpler example and see how we can convince Rust to generate the code we want (which is what I did for #23). It's a bit tricky, but doable. https://godbolt.org is a really nice tool for this!

I.e. reproduce a bare minimum set of traits and impls to reproduce the issue and see what you can do to make them converge in code generation.
