### ISSUE TITLE
Key derive macro triggers clippy warning on some nightlies

### ISSUE THREAD

**Issue by Roms1383** [udoprog/fixed-map#48]
Hi and thanks for this crate it's perfect for my use case :)
There's a minor issue originating from `clippy` on _some_ `nightly` only.
<details><summary>Click here for the logs</summary>

```powershell
error: non-local `impl` definition, they should be avoided as they go against expectation
  --> sys\src\interop\locale.rs:15:5
   |
15 |     Key,
   |     ^^^
   |
   = help: move this `impl` block outside the of the current constant `__IMPL_KEY_FOR_Locale`
   = note: an `impl` definition is non-local if it is nested inside an item and may impact type checking outside of that item. This can be the case if neither the trait or the self type are at the same nesting level as the `impl`
   = note: one exception to the rule are anon-const (`const _: () = { ... }`) at top-level module and anon-const at the same nesting as the trait or type
   = note: this lint may become deny-by-default in the edition 2024 and higher, see the tracking issue <https://github.com/rust-lang/rust/issues/120363>
   = note: the derive macro `Key` may come from an old version of the `fixed_map_derive` crate, try updating your dependency with `cargo update -p fixed_map_derive`
   = note: `-D non-local-definitions` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(non_local_definitions)]`
   = note: this error originates in the derive macro `Key` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `audioware-sys` (lib) due to 1 previous error
error: Recipe `qa` failed on line 92 with exit code 1
```

</details>

A quick fix suggested by `clippy` would be to add `#[allow(non_local_definitions)]` on `Key` generated impl block (see logs).

It's very trivial and non-blocking, but going around it in my codebase requires pinning nightly version in each and every commands, which is a bit cumbersome.

**Comment by Roms1383** [comment]
> It's very trivial and non-blocking, but going around it in my codebase requires pinning nightly version in each and every commands, which is a bit cumbersome.

As a side note, `clippy` accepts `-A non-local-definitions` arg as a simpler workaround.

**Comment by udoprog** [comment]
It's unclear to me why this triggers for you. Are you enabling this lint explicitly?

If so, it seems like many macros would be affected because wrapping the impl inside of a const block for encapsulation is a fairly common pattern.

**Comment by udoprog** [comment]
Note I'd still be prone to ignoring it by either allow:ing it or lifting the impls out of the const blocks (don't think we're using it anyways) if that helps. But it would be annoying if it's just a false positive which is temporarily broken on nightly.

**Comment by Roms1383** [comment]
Yes I hesitated to open an issue the first time it happened a couple of months ago, it could be a false positive. Let's see if the RFC gets settled and merged in edition 2024.

**Comment by udoprog** [comment]
Relates to rust-lang/rust#120363

**Comment by udoprog** [comment]
So the lint is not supported to trigger for anonymous blocks, fixed-map currently uses a named block. So I think it should be fixable simply by renaming the const variable to `_`.

**Comment by udoprog** [comment]
I just published `0.9.4`, please try it out. It should be using anonymous constant blocks.

**Comment by Roms1383** [comment]
I'll give it a try tonight or tomorrow morning, and provide feedback here, thanks for being so reactive!

**Comment by Roms1383** [comment]
It does work, as can be seen [from workflow run](https://github.com/cyb3rpsych0s1s/audioware/actions/runs/8741091982).
Thanks for addressing it so fast!
