### ISSUE TITLE
Entry api

### ISSUE THREAD

**Issue by msdrigg** [udoprog/fixed-map#5]
Love the work you've done on this crate. Have you thought about implementing the entry api for the map? I find it very useful and would like to use it with your crate.

Here's a link to the entry type if you aren't familiar https://doc.rust-lang.org/std/collections/hash_map/enum.Entry.html

**Comment by udoprog** [comment]
Thank you <3

I haven't personally needed it, but I'll keep this issue open so that people who wants to add it can!

**Comment by msdrigg** [comment]
Thanks! I might even make it myself if I get a bit more free time

**Comment by pitaj** [comment]
If a full entry API is hard to stomach, something like the following would cover most use cases:

    fn get_mut_or_insert_with(&mut self, key: K, default: Fn() -> V) -> &mut V:

**Comment by udoprog** [comment]
Thanks for the request and comments! Closing in favor of #11 to avoid having too many open issues about requested APIs.
